### ISSUE TITLE
Plexrequest it shows 'Failure No such image : linuxserver/plexrequestse:latest'

### ISSUE THREAD

**Issue by headrat** [TheLustriVA/portainer-templates-Nov-2022-collection#2]
**Describe the bug**
Plexrequest it shows 'Failure No such image : linuxserver/plexrequestse:latest'

**To Reproduce**
1. Once you've selected the template click on 'Deploy Container', you get error: plexrequest it shows 'Failure No such image  linuxserver/plexrequestse:latest'

**Expected behavior**
Deploy container 

**Desktop (please complete the following information):**
Portainer 2.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by headrat** [comment]
Seems like plexrequest has been removed, can't find it in the template list, hopefully this means it's being fixed :)

**Comment by TheLustriVA** [comment]
It's been replaced by what I think is its successor - Ombi. I tested it last night but forgot to mention it. Cheers again!
