### ISSUE TITLE
Dupes of pritunl

### ISSUE THREAD

**Issue by RyanLangston** [TheLustriVA/portainer-templates-Nov-2022-collection#3]
**Describe the bug**
There are several dupes of pritunl (in the deduped version)

**To Reproduce**
1. Add the app template
2. Go to app templates
3. Look up "pritunl"

**Expected behavior**
Should only be one pritunl

**Screenshots**
![image](https://user-images.githubusercontent.com/68302450/224400050-033a77f3-38f2-4e0a-b86a-a4e0fbf0242d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version Latest

**Smartphone (please complete the following information):**
 - Device:  iPhone XR
 - OS: 16.3
 - Browser Safari
 - Version latest

**Additional context**

**Comment by RyanLangston** [comment]
Just found duplicati dupes as well

**Comment by TheLustriVA** [comment]
There are a few more too, I've been meaning to clear them out so I might jump on that tonight. Cheers mate.

**Comment by TheLustriVA** [comment]
I've run a better dedupe on the file and made a new release. Hopefully that helps.

**Comment by RyanLangston** [comment]
Alright, thanks man! I'll test it out when I find the time!
