### ISSUE TITLE
"Failure: Unable to retrieve templates" after saving the new json URL in settings

### ISSUE THREAD

**Issue by danielhunt** [TheLustriVA/portainer-templates-Nov-2022-collection#4]
**Describe the bug**
After following the [final install step in the README](https://github.com/TheLustriVA/portainer-templates-Nov-2022-collection/blob/main/README.md?plain=1#L25), Portainer (v 2.18.2) is no longer able to load the list of templates.

The error displayed states `Failure - Unable to retrieve templates` (see screenshot)

![image](https://user-images.githubusercontent.com/99176/235901271-1786e7f6-611f-49b7-bb47-8fb460b70c15.png)

**To Reproduce**
1. Follow the three install steps in the README
2. Click on 'App Templates' within your environment in Portainer
3. See error in the toast notification on the top right of the screen

**Expected behavior**
The new (longer) list of templates should appear

**Comment by danielhunt** [comment]
Interestingly the [0.1.3](https://github.com/TheLustriVA/portainer-templates-Nov-2022-collection/tree/0.1.3) [json file](https://raw.githubusercontent.com/TheLustriVA/portainer-templates-Nov-2022-collection/0.1.3/mlva-templates-2.0-deduped.json) _does_ work

**Comment by timekills** [comment]
+1 to both v2.18.2 not working but 0.1.3 is working.
Much smaller list in the OG however...

**Comment by yarvnis** [comment]
try this:
https://raw.githubusercontent.com/TheLustriVA/portainer-templates-Nov-2022-collection/main/mlva-templates-2.0-deduped.json

may not be upto date, but definitely bigger list compared to 0.1.3

**Comment by danielhunt** [comment]
Confirmed as working - thanks for the quick resolution @TheLustriVA 👍 😄

**Comment by TheLustriVA** [comment]
I appreciate that mate. Wish I'd taken less than 3 months to figure that one out. 😂
